name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, bcmath, curl, dom, pdo_mysql, openssl
        ini-values: post_max_size=128M, upload_max_filesize=128M
        coverage: none

    - name: Install dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        cp .env.example .env
        php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /path/to/project
          git pull origin main
          composer install --no-dev
          php artisan migrate --force
          php artisan optimize
